# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-19 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('disable', models.BooleanField(default=False)),
                ('ctime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_admin',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('size', models.BigIntegerField()),
                ('path', models.TextField()),
                ('ctime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_file',
            },
        ),
    ]
