"""
    hint message for response
"""

MSG_LOGIN_SUCCESS = '登录成功'
MSG_LOGOUT_SUCCESS = '退出成功'
MSG_CHANGEPWD_SUCCESS = '修改密码成功'

ERR_EXCEPTION = '服务器异常'

ERR_LOGIN_INPUT = '请输入正确的用户名和密码'
ERR_LOGIN_USER = '用户名错误'
ERR_LOGIN_DISABLED = '用户被禁用'
ERR_LOGIN_PASSWORD = '密码错误'

ERR_NOT_AUTHORIZED = "未授权"

ERR_FORM_DATA = '操作失败，请检查您的输入数据'
ERR_RECORD_EXISTS = '记录已存在'

ERR_ACCOUNT_ORDER_NOT_EXIST = '委托不存在'
ERR_ACCOUNT_ORDER_OPERATION_DENIED = '委托操作非法'

ERR_TRADE_ORDER_NOT_EXIST = '订单不存在'
ERR_TRADE_ORDER_OPERATION_DENIED = '订单操作非法'
