# Generated by Django 2.0.4 on 2018-06-05 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=32, unique=True)),
                ('pwd', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('disable', models.BooleanField(default=False)),
                ('ctime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_admin',
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ctime', models.BigIntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.Admin')),
            ],
            options={
                'db_table': 'tb_admin_role',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=256)),
                ('size', models.BigIntegerField()),
                ('ctime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_file',
            },
        ),
        migrations.CreateModel(
            name='Lever',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lever', models.IntegerField(unique=True)),
                ('wline', models.DecimalField(decimal_places=2, max_digits=2)),
                ('sline', models.DecimalField(decimal_places=2, max_digits=2)),
                ('ofmin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ofrate', models.DecimalField(decimal_places=6, max_digits=6)),
                ('dfrate', models.DecimalField(decimal_places=6, max_digits=6)),
                ('psrate', models.DecimalField(decimal_places=6, max_digits=6)),
                ('mmin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mmax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.IntegerField(default=0)),
                ('disable', models.BooleanField(default=True)),
                ('ctime', models.BigIntegerField()),
                ('mtime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_lever',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('path', models.CharField(blank=True, max_length=128)),
                ('order', models.IntegerField(default=0)),
                ('disable', models.BooleanField(default=False)),
                ('ctime', models.BigIntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='adb.Module')),
            ],
            options={
                'db_table': 'tb_module',
            },
        ),
        migrations.CreateModel(
            name='PayAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('account', models.CharField(max_length=32)),
                ('disable', models.BooleanField(default=True)),
                ('ctime', models.BigIntegerField()),
                ('mtime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_pay_account',
            },
        ),
        migrations.CreateModel(
            name='PayGateway',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('icon', models.CharField(max_length=32)),
                ('order', models.IntegerField(default=0)),
                ('disable', models.BooleanField(default=True)),
                ('ctime', models.BigIntegerField()),
                ('mtime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_pay_gateway',
            },
        ),
        migrations.CreateModel(
            name='QuoteAgent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('disable', models.BooleanField(default=True)),
                ('htime', models.BigIntegerField()),
                ('ctime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_quote_agent',
            },
        ),
        migrations.CreateModel(
            name='QuoteServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('disable', models.BooleanField(default=False)),
                ('ctime', models.BigIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.QuoteAgent')),
            ],
            options={
                'db_table': 'tb_quote_server',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('disable', models.BooleanField(default=False)),
                ('ctime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_role',
            },
        ),
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ctime', models.BigIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.Module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.Role')),
            ],
            options={
                'db_table': 'tb_role_module',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('jianpin', models.CharField(max_length=16)),
                ('quanpin', models.CharField(max_length=32)),
                ('status', models.CharField(default='open', max_length=8)),
                ('limit', models.CharField(default='normal', max_length=8)),
                ('ctime', models.BigIntegerField()),
                ('mtime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_stock',
            },
        ),
        migrations.CreateModel(
            name='TradeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('account', models.CharField(max_length=16, unique=True)),
                ('lmoney', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cfmin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cfrate', models.DecimalField(decimal_places=6, max_digits=6)),
                ('tfrate', models.DecimalField(decimal_places=6, max_digits=6)),
                ('rfmin', models.DecimalField(decimal_places=6, max_digits=10)),
                ('rfrate', models.DecimalField(decimal_places=6, max_digits=6)),
                ('tpwd', models.CharField(max_length=16)),
                ('cpwd', models.CharField(max_length=16)),
                ('dept', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=16)),
                ('disable', models.BooleanField(default=True)),
                ('ctime', models.BigIntegerField()),
                ('mtime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_trade_account',
            },
        ),
        migrations.CreateModel(
            name='TradeAgent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('disable', models.BooleanField(default=False)),
                ('htime', models.BigIntegerField()),
                ('ctime', models.BigIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.TradeAccount')),
            ],
            options={
                'db_table': 'tb_trade_agent',
            },
        ),
        migrations.CreateModel(
            name='TradeFee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=8)),
                ('detail', models.CharField(blank=True, max_length=64)),
                ('nmoney', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amoney', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_trade_fee',
            },
        ),
        migrations.CreateModel(
            name='TradeLever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lever', models.IntegerField()),
                ('wline', models.DecimalField(decimal_places=2, max_digits=2)),
                ('sline', models.DecimalField(decimal_places=2, max_digits=2)),
                ('ofmin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ofrate', models.DecimalField(decimal_places=6, max_digits=6)),
                ('dfrate', models.DecimalField(decimal_places=6, max_digits=6)),
                ('psrate', models.DecimalField(decimal_places=6, max_digits=6)),
                ('mmin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mmax', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tb_trade_lever',
            },
        ),
        migrations.CreateModel(
            name='TradeMargin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=16)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_trade_margin',
            },
        ),
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordern', models.CharField(max_length=16)),
                ('otype', models.CharField(max_length=8)),
                ('ptype', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=8)),
                ('ocode', models.CharField(max_length=16)),
                ('oprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ocount', models.IntegerField()),
                ('otime', models.BigIntegerField()),
                ('dcode', models.CharField(max_length=16, null=True)),
                ('dprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dcount', models.IntegerField(null=True)),
                ('dtime', models.BigIntegerField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.TradeAccount')),
            ],
            options={
                'db_table': 'tb_trade_order',
            },
        ),
        migrations.CreateModel(
            name='TradeServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('ip', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('disable', models.BooleanField(default=False)),
                ('ctime', models.BigIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.TradeAgent')),
            ],
            options={
                'db_table': 'tb_trade_server',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=16, unique=True)),
                ('pwd', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disable', models.BooleanField(default=False)),
                ('ctime', models.BigIntegerField()),
                ('ltime', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='UserBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('account', models.CharField(max_length=32)),
                ('deleted', models.BooleanField(default=False)),
                ('ctime', models.BigIntegerField()),
                ('mtime', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.User')),
            ],
            options={
                'db_table': 'tb_user_bank',
            },
        ),
        migrations.CreateModel(
            name='UserBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('item', models.CharField(max_length=16)),
                ('detail', models.CharField(max_length=64)),
                ('bmoney', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lmoney', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctime', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.User')),
            ],
            options={
                'db_table': 'tb_user_bill',
            },
        ),
        migrations.CreateModel(
            name='UserCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='paying', max_length=16)),
                ('ctime', models.BigIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.PayAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.User')),
            ],
            options={
                'db_table': 'tb_user_charge',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='unused', max_length=16)),
                ('ctime', models.BigIntegerField()),
                ('etime', models.BigIntegerField()),
                ('utime', models.BigIntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.User')),
            ],
            options={
                'db_table': 'tb_user_coupon',
            },
        ),
        migrations.CreateModel(
            name='UserDraw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('account', models.CharField(max_length=32)),
                ('status', models.CharField(default='paying', max_length=16)),
                ('ctime', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.User')),
            ],
            options={
                'db_table': 'tb_user_draw',
            },
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('ctime', models.BigIntegerField()),
                ('dtime', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.User')),
            ],
            options={
                'db_table': 'tb_user_stock',
            },
        ),
        migrations.CreateModel(
            name='UserTrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('hcount', models.IntegerField(default=0)),
                ('fcount', models.IntegerField(default=0)),
                ('oprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ocount', models.IntegerField()),
                ('bprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bcount', models.IntegerField(null=True)),
                ('sprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('scount', models.IntegerField(null=True)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ofee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ddays', models.IntegerField(default=0)),
                ('dfee', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tprofit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sprofit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(default='tobuy', max_length=16)),
                ('ctime', models.BigIntegerField()),
                ('ftime', models.BigIntegerField(null=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adb.UserCoupon')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.User')),
            ],
            options={
                'db_table': 'tb_user_trade',
            },
        ),
        migrations.AddField(
            model_name='trademargin',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.UserTrade'),
        ),
        migrations.AddField(
            model_name='tradelever',
            name='trade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adb.UserTrade'),
        ),
        migrations.AddField(
            model_name='tradefee',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.UserTrade'),
        ),
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(through='adb.RoleModule', to='adb.Module'),
        ),
        migrations.AddField(
            model_name='payaccount',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.PayGateway'),
        ),
        migrations.AddField(
            model_name='adminrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb.Role'),
        ),
        migrations.AddField(
            model_name='admin',
            name='roles',
            field=models.ManyToManyField(through='adb.AdminRole', to='adb.Role'),
        ),
    ]
